# Generated by Django 4.2.11 on 2024-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_customuser_location_customuser_account_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
