# Generated by Django 4.2.11 on 2024-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_customuser_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_code',
            field=models.PositiveIntegerField(default=933331),
        ),
    ]
